codon bugs
10 codon bugs.
The error messages are listed in log.txt in each bug directory.  We also listed in the following.

codon_program0.py:5:4-8: error: 's234DI58I' object has no attribute 'D81836891'
codon_program0.py:10:2-40: error: during the realization of B99q2s0(self: s234DI58I, s843oO1: bool, Cb5pZ943U: bool)
codon_program1.py:7:22: error: syntax error, unexpected '('
codon_program2.py:4:14: error: syntax error, unexpected 'or'
codon_program3.py:7:31: error: syntax error, unexpected 'and'
codon_program4.py:4:47-52: error: name 'bytes' is not defined
codon_program5.py:5:5-9: error: 'T12Hb789' object has no attribute 'BR280BRF'
codon_program5.py:8:2-22: error: during the realization of D2z16jwnb8(self: T12Hb789)
codon_program6.py:5:4-8: error: 'ceGQzN5O7' object has no attribute 'n7XHcC587'
codon_program6.py:8:2-23: error: during the realization of op7Igj8j(self: ceGQzN5O7)
ValueError: optional is None

Raised from: std.internal.types.optional.unwrap:0
/home/qurong/.codon/lib/codon/stdlib/internal/types/optional.codon:80:5

Backtrace:
  [0x7f08afd228b5] GCC_except_table74 at /home/qurong/.codon/lib/codon/stdlib/internal/types/optional.codon:80:5
  [0x7f08afd2294f] GCC_except_table74 at /home/qurong/codes-generated-by-grammar/python/issues/codon/python_7/codon_program7.py:7:29
  [0x7f08afd2776e] GCC_except_table74 at /home/qurong/codes-generated-by-grammar/python/issues/codon/python_7/codon_program7.py:15:20
test_codon_issues.sh: line 8: 303271 Aborted                 (core dumped) ../../../../../.codon/bin/codon run codon_program${i}.py >> codenExpected.txt
ValueError: optional is None

Raised from: std.internal.types.optional.unwrap:0
/home/qurong/.codon/lib/codon/stdlib/internal/types/optional.codon:80:5

Backtrace:
  [0x7f63d7191865] GCC_except_table73 at /home/qurong/.codon/lib/codon/stdlib/internal/types/optional.codon:80:5
  [0x7f63d71918ee] GCC_except_table73 at /home/qurong/codes-generated-by-grammar/python/issues/codon/python_8/codon_program8.py:6:27
  [0x7f63d71966dc] GCC_except_table73 at /home/qurong/codes-generated-by-grammar/python/issues/codon/python_8/codon_program8.py:13:2
test_codon_issues.sh: line 8: 303366 Aborted                 (core dumped) ../../../../../.codon/bin/codon run codon_program${i}.py >> codenExpected.txt
codon_program9.py:7:20-34: error: name 'QD31jzVqwcount' is not defined
codon_program9.py:8:8-22: error: name 'QD31jzVqwcount' is not defined
codon_program10.py:5:1: error: unexpected dedent